language: node_js
node_js: '8'
before_install:
  - npm install lerna
  - lerna bootstrap
  - npm install codecov
before_script:
  - lerna run prepare
script:
  - npm run test
after_success:
  - npx nyc --reporter=lcov npm test
  - npx codecov
