// Generated by CoffeeScript 1.6.3
(function() {
  var exec, fs, program;

  fs = require('fs');

  program = require('commander');

  exec = require('child_process').exec;

  program.option('-s, --source <directory>', 'The css source directory').parse(process.argv);

}).call(this);
